language: php

sudo: false

dist: trusty

git:
  depth: 5

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - mysql -e 'CREATE DATABASE phpunit;'
  - composer self-update
  - composer install

script:
  - composer test
